---
- hosts: server
  gather_facts: yes
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'

  handlers:
  - include: handlers/main.yml

  roles:
    - add-user

- hosts: clients
  gather_facts: yes
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'

  handlers:
  - include: handlers/main.yml

  roles:
    - deploy-user
