---
- hosts: all
  gather_facts: no
  vars:
    taskd_org: SmirnovLabs
    taskd_client: Test User3
  vars_files:
    - 'defaults/main.yml'

  handlers:
  - name: restart taskd
    service:
      name: taskd
      state: restarted
    ignore_errors: yes

  roles:
    - add-user
    - deploy-user
