---
- hosts: all
  gather_facts: yes
  vars_files:
    - 'vars/main.yml'

  handlers:
  - name: restart taskd
    service:
      name: taskd
      state: restarted
    ignore_errors: yes

  roles:
    - base
    - certs
    - config
#    - init
