---
- name: install the latest version of task
  package:
    name: task
    state: latest

- name: sync the fetched task configs on each host
  synchronize: >
    src=fetch/
    dest=~/.task/

- name: Write ~/.taskrc
  template:
    src: taskrc
    dest: ~/.taskrc
    force: no
